repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.14.0
    hooks:
      - id: eslint
        args:
          [
            --fix,
            --config,
            .eslintrc.js,
            --cache,
          ]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@^7.6.0
          - "@typescript-eslint/eslint-plugin@^4.9.0"
          - "@typescript-eslint/parser"
